/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppProjectionsRouteImport } from './routes/_app/projections'
import { Route as AppIncomeRouteImport } from './routes/_app/income'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppExpensesRecurringRouteImport } from './routes/_app/expenses/recurring'
import { Route as AppExpensesPlannedRouteImport } from './routes/_app/expenses/planned'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectionsRoute = AppProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRecurringRoute = AppExpensesRecurringRouteImport.update({
  id: '/expenses/recurring',
  path: '/expenses/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesPlannedRoute = AppExpensesPlannedRouteImport.update({
  id: '/expenses/planned',
  path: '/expenses/planned',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/budgets': typeof AppBudgetsRoute
  '/income': typeof AppIncomeRoute
  '/projections': typeof AppProjectionsRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
  '/expenses/planned': typeof AppExpensesPlannedRoute
  '/expenses/recurring': typeof AppExpensesRecurringRoute
  '/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/budgets': typeof AppBudgetsRoute
  '/income': typeof AppIncomeRoute
  '/projections': typeof AppProjectionsRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/expenses/planned': typeof AppExpensesPlannedRoute
  '/expenses/recurring': typeof AppExpensesRecurringRoute
  '/expenses': typeof AppExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/projections': typeof AppProjectionsRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/expenses/planned': typeof AppExpensesPlannedRoute
  '/_app/expenses/recurring': typeof AppExpensesRecurringRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/budgets'
    | '/income'
    | '/projections'
    | '/savings'
    | '/settings'
    | '/expenses/planned'
    | '/expenses/recurring'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/budgets'
    | '/income'
    | '/projections'
    | '/savings'
    | '/settings'
    | '/'
    | '/expenses/planned'
    | '/expenses/recurring'
    | '/expenses'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/budgets'
    | '/_app/income'
    | '/_app/projections'
    | '/_app/savings'
    | '/_app/settings'
    | '/_app/'
    | '/_app/expenses/planned'
    | '/_app/expenses/recurring'
    | '/_app/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projections': {
      id: '/_app/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AppProjectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/recurring': {
      id: '/_app/expenses/recurring'
      path: '/expenses/recurring'
      fullPath: '/expenses/recurring'
      preLoaderRoute: typeof AppExpensesRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/planned': {
      id: '/_app/expenses/planned'
      path: '/expenses/planned'
      fullPath: '/expenses/planned'
      preLoaderRoute: typeof AppExpensesPlannedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppProjectionsRoute: typeof AppProjectionsRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpensesPlannedRoute: typeof AppExpensesPlannedRoute
  AppExpensesRecurringRoute: typeof AppExpensesRecurringRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetsRoute: AppBudgetsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppProjectionsRoute: AppProjectionsRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpensesPlannedRoute: AppExpensesPlannedRoute,
  AppExpensesRecurringRoute: AppExpensesRecurringRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
